### ISSUE TITLE
ESPresence or this?

### ISSUE THREAD

**Issue by nmajin** [dalehumby/ESPHome-Apple-Watch-detection#10]
I only care about presence detection with my Apple Watch and it appears https://espresense.com/ is doing the same as this solution. Trying to determine which method I should go with.

Thanks

**Comment by dalehumby** [comment]
ESPresense is a great project, and if it works for you then that's amazing.

For me, I already have a house full of ESP devices running ESPHome for e.g. receiving Bluetooth temp/humidity, transmitting IR codes to my TV, etc. I wanted a presence detection solution that builds on top of that infrastructure, instead of needing to add extra ESP32's which can only be used for presence detection.

That said, ESP's are pretty cheap so dedicated devices is not that expensive for a few rooms. But I try consolidate where I can so I don't have to keep so many devices up to date, powered, hidden neatly.

Hope that helps.

**Comment by nmajin** [comment]
Thanks for the info and thanks for the work you’ve done with this solution. I tried our ESPresence and out of the box it’s not working consistently (distance attribute seems to be all over the place and never registers “away”). Anyway, will look into it more and possibly try out this solution if I can’t get ESPresence going.

**Comment by cbhiii** [comment]
I left ESPresense and come to this project. ESPresense was not working for me reliably. This seems to work much better and I don't have to find my wife's and my own apple watch to enter them in for it to work. It just checks for all apple watches (humans) in a room which I like.

**Comment by nmajin** [comment]
> I left ESPresense and come to this project. ESPresense was not working for me reliably. This seems to work much better and I don't have to find my wife's and my own apple watch to enter them in for it to work. It just checks for all apple watches (humans) in a room which I like.

With the recent updates, ESPresense has been super reliable and I’m just filtering out events for my watch, which is all I care about, so going to assume that helps. I was going to setup the AppDaemon for it but considering how it’s working now, I don’t think I’m going to add more complexity to it now.
